version: '3'
services:
  unifi:
    image: mgcrea/unifi:5
    container_name: unifi
    environment:
      - TZ=Europe/Paris
    network_mode: "host"
    privileged: true
    volumes:
      - ./data/data:/usr/lib/unifi/data
      - ./data/logs:/usr/lib/unifi/logs
      - ./data/work:/usr/lib/unifi/work
    ports:
      - "8880:8880/tcp"
      - "8443:8443/tcp"
      - "8080:8080/tcp"
      - "8843:8843/tcp"
      - "3478:3478/udp"
    restart: always